# Generated by Django 5.2 on 2025-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_todolist_todoitem_sharedtodolist_delete_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
